<#ftl output_format="plainText">
-- This file was autogenerated from ${filename} by bin2vhdl - do not edit
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package ${name!test} is
  type data_t is array(0 to ${(values?size)-1}) of std_logic_vector(${word_width-1} downto 0);
  constant_data :data_t := ( 
  <#list values as x>
  X"${hex(x,word_width)}"<#if (!(x?is_last))>,</#if>
  </#list>
  );

end ${name!test};


